# TÍTULO PROYECTO INICIAL 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
Acciones=np.random.randn(5,4)
Acciones

array([[-0.53780915,  0.1103837 , -0.39329896,  1.19314604],
       [-0.48793199, -0.17955827, -0.5211153 ,  1.24133515],
       [ 3.31449581,  0.35713817,  0.83152412, -0.37539923],
       [ 1.51321988, -2.39589526, -1.17442749, -0.83408266],
       [-1.01800823, -0.006483  ,  0.23958548,  0.4553894 ]])

In [3]:
Acciones.mean() #esto es desde el modulo de pandas

0.06661040971415849

In [4]:
np.mean(Acciones) #el mismo calculo del anterior pero con el modulo numpy

0.06661040971415849

In [5]:
Acciones.mean(axis=1) #axis=1 significa calculos por fila

array([ 0.09310541,  0.0131824 ,  1.03193972, -0.72279638, -0.08237909])

In [6]:
Acciones.mean(axis=0) #axis=0 significa calculos por columna

array([ 0.55679326, -0.42288294, -0.20354643,  0.33607774])

In [7]:
np.median(Acciones)

-0.09302063928082323

In [8]:
np.median(Acciones,0)

array([-0.48793199, -0.006483  , -0.39329896,  0.4553894 ])

In [9]:
np.std(Acciones)

1.1667440097257604

In [10]:
np.std(Acciones,0)

array([1.63029324, 1.00181632, 0.68515735, 0.8299117 ])

In [11]:
np.var(Acciones)

1.3612915842309454

In [12]:
np.var(Acciones,0)

array([2.65785605, 1.00363593, 0.4694406 , 0.68875343])

In [13]:
np.var(Acciones,1)

array([0.46125758, 0.52052445, 1.9215472 , 2.00384597, 0.31850456])

In [14]:
from scipy import stats

In [15]:
stats.mode(Acciones)

ModeResult(mode=array([[-1.01800823, -2.39589526, -1.17442749, -0.83408266]]), count=array([[1, 1, 1, 1]]))

In [16]:
datos=np.array([1,2,6,6,2,6,10,11,13,25])

In [17]:
datos

array([ 1,  2,  6,  6,  2,  6, 10, 11, 13, 25])

In [18]:
stats.mode(datos)

ModeResult(mode=array([6]), count=array([3]))

In [19]:
np.corrcoef(Acciones)

array([[ 1.        ,  0.98150481, -0.7707271 , -0.34907119,  0.6695783 ],
       [ 0.98150481,  1.        , -0.65870648, -0.1697341 ,  0.57878785],
       [-0.7707271 , -0.65870648,  1.        ,  0.82557314, -0.9613066 ],
       [-0.34907119, -0.1697341 ,  0.82557314,  1.        , -0.75864709],
       [ 0.6695783 ,  0.57878785, -0.9613066 , -0.75864709,  1.        ]])

In [20]:
data_acciones=pd.DataFrame(Acciones,index=['fila1','fila2','fila3','fila4','fila5'],
                           columns=['Acc1','Acc2','Acc3','Acc4'])
data_acciones

Acc1      Acc2      Acc3      Acc4
fila1 -0.537809  0.110384 -0.393299  1.193146
fila2 -0.487932 -0.179558 -0.521115  1.241335
fila3  3.314496  0.357138  0.831524 -0.375399
fila4  1.513220 -2.395895 -1.174427 -0.834083
fila5 -1.018008 -0.006483  0.239585  0.455389

In [21]:
data_acciones.describe()

Acc1      Acc2      Acc3      Acc4
count  5.000000  5.000000  5.000000  5.000000
mean   0.556793 -0.422883 -0.203546  0.336078
std    1.822723  1.120065  0.766029  0.927869
min   -1.018008 -2.395895 -1.174427 -0.834083
25%   -0.537809 -0.179558 -0.521115 -0.375399
50%   -0.487932 -0.006483 -0.393299  0.455389
75%    1.513220  0.110384  0.239585  1.193146
max    3.314496  0.357138  0.831524  1.241335

FIN DE LA CLASE

In [22]:
import cufflinks as cf

ModuleNotFoundError: No module named 'cufflinks'

In [23]:
import chart_studio.plotly as py

ModuleNotFoundError: No module named 'chart_studio'